name: Docker Image CI

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*.*.*'
  # pull_request:
  #   branches: [ main ]

jobs:
  ci-image:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      IMAGE_NAME: go-dev
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Debug Tag
        run: echo ${{ env.TAG }}
      - name: Login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            alinuxsa/${env.IMAGE_NAME}:${{ env.TAG }}
            alinuxsa/${env.IMAGE_NAME}:latest 
