name: Docker Image CI

on:
  workflow_dispatch: 
  push:
    tags:
      - "v*.*"
  # pull_request:
  #   branches: [ main ]

env:
  IMAGE_NAME: go-dev

jobs:
  ci-image:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag
        id: get_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            alinuxsa/go-dev:${{ steps.get_version.outputs.tag }}
            alinuxsa/go-dev:latest 
